export enum VoiceErrors {
    USER_NOT_CONNECTED = 'USER_NOT_CONNECTED',
    BOT_NOT_CONNECTED = 'BOT_NOT_CONNECTED',
    USER_IN_DIFFERENT_CHANNEL = 'USER_IN_DIFFERENT_CHANNEL',
    MISSING_CONNECT_PERMS = 'MISSING_CONNECT_PERMS',
    PAUSE_FAILURE = 'PAUSE_FAILURE',
    RESUME_FAILURE = 'RESUME_FAILURE',
}

export enum PlayErrors {
    NOT_VALID_LINK = 'NOT_VALID_LINK',
    VIDEO_NOT_AVAILABLE = 'VIDEO_NOT_AVAILABLE',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum MinecraftErrors {
    ERROR_FETCHING_STATUS = 'ERROR_FETCHING_STATUS',
}
