export enum VoiceInfo {
    SUCCESSFUL_JOIN = 'SUCCESSFUL_JOIN',
    SUCCESSFUL_LEAVE = 'SUCCESSFUL_LEAVE',
    SUCCESSFUL_PAUSE = 'SUCCESSFUL_PAUSE',
    SUCCESSFUL_RESUME = 'SUCCESSFUL_RESUME',
    SHOWING_QUEUE = 'SHOWING_QUEUE',
    CLEARING_QUEUE = 'CLEARING_QUEUE',
    SKIPPING = 'SKIPPING',
    EMPTY_QUEUE = 'EMPTY_QUEUE',
}

export enum PlaySuccesses {
    SUCCESSFUL_QUEUE = 'SUCCESSFUL_QUEUE',
    SUCCESSFUL_PLAY = 'SUCCESSFUL_PLAY',
}
